### ISSUE TITLE
readModuleAndServiceRegistedInSection 注册service协议实现类有问题

### ISSUE THREAD

**Issue by haoyuxingchen123** [NianJi/AppLord#4]
- (void)readModuleAndServiceRegistedInSection
{
    NSArray<NSString *> *dataListInSection = AppLordReadConfigFromSection("AppLord");
    for (NSString *item in dataListInSection) {
        NSArray *components = [item componentsSeparatedByString:@":"];
        if (components.count >= 2) {
            NSString *type = components[0];
            if ([type isEqualToString:@"M"]) {
                NSString *modName = components[1];
                Class modCls = NSClassFromString(modName);
                if (modCls) {
                    [self registerModule:modCls];
                }
            } else if ([type isEqualToString:@"S"] && components.count == 3) {
                NSString *serName = components[1];
                 NSString *serImplName =  **components[1]**;
                Protocol *serPro = NSProtocolFromString(serName);
                Class serCls = NSClassFromString(serImplName);
                if (serPro && serCls) {
                    [self registerService:serPro withImpl:serCls];
                }
            }
        }
    }

您好nianji，在使用您的框架的时候发现有个问题，是不是应该将NSString *serImplName = components[1] 改为NSString *serImplName = components[2]， 就是这里应该是service 协议的实现类名。

**Comment by NianJi** [comment]
已修复，低级错误😅
