### ISSUE TITLE
想问一下对于这些service接口文件是放在哪里？

### ISSUE THREAD

**Issue by coderyi** [NianJi/AppLord#6]
是需要放在一个单独仓库以供业务模块依赖吗？这样也比较尴尬啊？万一service方法中的入参和返回值又依赖其他仓库怎么办？
冒昧提问，还请见谅，非常期待您的解答

**Comment by NianJi** [comment]
单独放在一个仓库，这个仓库不需要依赖别的模块， 入参和返回值最好是系统已有类型，如果是自定义类型，也可以做到不依赖，就是再定义一个protocol表示那个类型。

**Comment by coderyi** [comment]
好的 谢谢
